name: "snmp_sensor"
version: "1.0.0"
authors: ["Velitel & ChatGPT"]

files:
  - snmp_sensor.cpp
  - snmp_sensor.h
  - snmp_client.cpp
  - snmp_client.h
  - sensor.py
  - __init__.py

requirements: []

esphome:
  # hlavní entrypoint komponenty
  components:
    - snmp_sensor
